### Data Manipulation and Analysis with Pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Chocolate_Sales.csv')
## fecth the first 5 rows
df.head(5)

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69

In [18]:
df.tail(5)

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
199995,ORD-053460,70% Dark Bar,Australia,Retail,Beatriz Souza,2022-05-27,10.6,3.39,186.19,125,418.56
199996,ORD-010743,Truffle Gift Box,India,Wholesale,Arjun Mehta,2022-09-06,17.3,3.07,42.28,148,366.47
199997,ORD-049690,Salted Caramel Bar,Japan,Online,Arjun Mehta,2022-06-16,18.3,2.74,100.19,149,329.79
199998,ORD-189637,85% Dark Bar,Japan,Wholesale,Rohan Patel,2022-10-14,9.3,14.30,29.96,24,304.51
199999,ORD-061616,Mint Dark Bar,Australia,Retail,Hannah Müller,2022-01-25,7.2,3.01,270.86,131,366.91

In [19]:
df.describe()

        Discount_Pct  Price_per_Box  Marketing_Spend  Boxes_Shipped
count  199511.000000  199543.000000    199539.000000  200000.000000
mean       13.107457       5.911507        95.450141     139.584105
std         6.374477       4.954976        66.243760     118.665393
min         0.000000       2.040000         4.300000   -1642.000000
25%         8.300000       2.950000        52.270000      67.000000
50%        12.600000       3.280000        78.850000     113.000000
75%        17.500000       4.570000       118.710000     180.000000
max        38.300000      21.650000       798.222443    3811.000000

In [20]:
df.dtypes

Order_ID               str
Product                str
Country                str
Channel                str
Salesperson            str
Order_Date             str
Discount_Pct       float64
Price_per_Box      float64
Marketing_Spend    float64
Boxes_Shipped        int64
Amount                 str
dtype: object

In [21]:
## Handling Missing values
df.isnull().any(axis=1) ## True = Missing value

0         False
1         False
2         False
3         False
4         False
          ...
199995    False
199996    False
199997    False
199998    False
199999    False
Length: 200000, dtype: bool

In [6]:
df.isnull().sum()

Order_ID                  0
Product                   0
Country                   0
Channel                   0
Salesperson               0
Order_Date              437
Discount_Pct            489
Price_per_Box           457
Marketing_Spend         461
Boxes_Shipped             0
Amount                    0
Price_per_Box_fillNA      0
dtype: int64

In [46]:
df_filled=df.fillna(0)

In [4]:
### filling missing value with the mean of the 

df['Price_per_Box_fillNA'] = df['Price_per_Box'].fillna(df['Price_per_Box'].mean())
df.head()

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_fillNA
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75

In [49]:
df.dtypes

Order_ID                    str
Product                     str
Country                     str
Channel                     str
Salesperson                 str
Order_Date                  str
Discount_Pct            float64
Price_per_Box           float64
Marketing_Spend         float64
Boxes_Shipped             int64
Amount                      str
Price_per_Box_fillNA    float64
dtype: object

In [63]:
# Renames Columns

df = df.rename(columns={'Order_Date':'Order_day'})
df.head()

,Order_ID,Product,Country,Channel,Salesperson,Order_day,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_fillNA
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75

In [65]:
## change data types
# df.dtypes
# df['Discount_Pct_new'] = df['Discount_Pct'].fillna(df['Discount_Pct'].mean()).astype(int)
# df.head(5)
df['Discount_Pct_new'] = df['Discount_Pct'].fillna(df['Discount_Pct'].mean()).astype(int)
df.head(5)

,Order_ID,Product,Country,Channel,Salesperson,Order_day,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_fillNA,Discount_Pct_new
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72,3
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30,9
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21,4
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66,15
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75,4

In [72]:
# df['New_Discount_Pct'] = df['Discount_Pct'].apply(lambda x:x*2)
# df
df['New_Discount_Pct'] = df['Discount_Pct'].apply(lambda x:x*2)
df.head()

,Order_ID,Product,Country,Channel,Salesperson,Order_day,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_fillNA,Discount_Pct_new,New_Discount_Pct
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72,3,7.0
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30,9,18.8
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21,4,9.8
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66,15,30.0
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75,4,8.8

In [74]:
df.head(5)

,Order_ID,Product,Country,Channel,Salesperson,Order_day,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_fillNA,Discount_Pct_new,New_Discount_Pct
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72,3,7.0
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30,9,18.8
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21,4,9.8
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66,15,30.0
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75,4,8.8

In [113]:
 ## determine mean based on the something common like same_product mean,same things etccc
grouped_mean = df.groupby('Product')['Marketing_Spend'].mean()
print(grouped_mean)

Product
70% Dark Bar            95.288753
85% Dark Bar            95.147741
Almond Crunch Bar       95.184821
Choco Coins Bag         95.528734
Hazelnut Milk Bar       95.542985
Milk Classic Bar        94.588577
Mint Dark Bar           94.690962
Mixed Assortment Box    96.392013
Pralines Gift Box       96.160074
Salted Caramel Bar      95.167710
Truffle Gift Box        95.246787
White Choco Bar         97.580173
Name: Marketing_Spend, dtype: float64

In [ ]:
## grouped of product sum,mean etccc
grouped_sum = df.groupby(['Country','Product'])['Boxes_Shipped'].sum()
print(grouped_sum)

Country    Product
Australia  70% Dark Bar            2978900
           85% Dark Bar             325628
           Almond Crunch Bar        648581
           Choco Coins Bag          523717
           Hazelnut Milk Bar        237727
           Milk Classic Bar         704705
           Mint Dark Bar            400709
           Mixed Assortment Box    2203685
           Pralines Gift Box        653562
           Salted Caramel Bar       317377
           Truffle Gift Box        2163760
           White Choco Bar          357223
Brazil     70% Dark Bar            2586765
           85% Dark Bar             295644
           Almond Crunch Bar        559590
           Choco Coins Bag          450863
           Hazelnut Milk Bar        221618
           Milk Classic Bar         595482
           Mint Dark Bar            339583
           Mixed Assortment Box    1892929
           Pralines Gift Box        573965
           Salted Caramel Bar       260045
           Truffle Gift Box        1899765
           White Choco Bar          324499
Germany    70% Dark Bar             786116
           85% Dark Bar              85493
           Almond Crunch Bar        173318
           Choco Coins Bag          152326
           Hazelnut Milk Bar         67922
           Milk Classic Bar         189617
           Mint Dark Bar            100756
           Mixed Assortment Box     614347
           Pralines Gift Box        168269
           Salted Caramel Bar        85184
           Truffle Gift Box         579244
           White Choco Bar           94680
India      70% Dark Bar             445277
           85% Dark Bar              50616
           Almond Crunch Bar        101964
           Choco Coins Bag           82377
           Hazelnut Milk Bar         37847
           Milk Classic Bar         108052
           Mint Dark Bar             63577
           Mixed Assortment Box     338156
           Pralines Gift Box         98518
           Salted Caramel Bar        48367
           Truffle Gift Box         330515
           White Choco Bar           54234
Japan      70% Dark Bar             380142
           85% Dark Bar              45203
           Almond Crunch Bar        101143
           Choco Coins Bag           79842
           Hazelnut Milk Bar         31214
           Milk Classic Bar          99034
           Mint Dark Bar             51879
           Mixed Assortment Box     285372
           Pralines Gift Box         86558
           Salted Caramel Bar        39862
           Truffle Gift Box         294196
           White Choco Bar           49282
Name: Boxes_Shipped, dtype: int64

In [81]:
df.groupby(['Country','Product'])['Boxes_Shipped'].mean()

Country    Product
Australia  70% Dark Bar             98.567269
           85% Dark Bar             89.679978
           Almond Crunch Bar       154.903511
           Choco Coins Bag         178.074464
           Hazelnut Milk Bar        97.830041
           Milk Classic Bar         93.848049
           Mint Dark Bar            81.115182
           Mixed Assortment Box    223.588170
           Pralines Gift Box       111.187819
           Salted Caramel Bar      115.451801
           Truffle Gift Box        144.549402
           White Choco Bar         108.843083
Brazil     70% Dark Bar            150.550867
           85% Dark Bar            135.990800
           Almond Crunch Bar       230.568603
           Choco Coins Bag         267.257261
           Hazelnut Milk Bar       153.368858
           Milk Classic Bar        142.391679
           Mint Dark Bar           122.504690
           Mixed Assortment Box    332.910482
           Pralines Gift Box       165.598673
           Salted Caramel Bar      175.706081
           Truffle Gift Box        223.055653
           White Choco Bar         167.095263
Germany    70% Dark Bar             95.914592
           85% Dark Bar             85.237288
           Almond Crunch Bar       147.004241
           Choco Coins Bag         180.695136
           Hazelnut Milk Bar       101.984985
           Milk Classic Bar         92.903969
           Mint Dark Bar            77.326170
           Mixed Assortment Box    220.670618
           Pralines Gift Box       107.657710
           Salted Caramel Bar      114.187668
           Truffle Gift Box        142.495449
           White Choco Bar         107.590909
India      70% Dark Bar             80.013836
           85% Dark Bar             70.202497
           Almond Crunch Bar       123.443099
           Choco Coins Bag         138.681818
           Hazelnut Milk Bar        80.697228
           Milk Classic Bar         74.673117
           Mint Dark Bar            66.088358
           Mixed Assortment Box    178.634971
           Pralines Gift Box        89.724954
           Salted Caramel Bar       97.711111
           Truffle Gift Box        116.051615
           White Choco Bar          90.996644
Japan      70% Dark Bar            104.578267
           85% Dark Bar             95.566596
           Almond Crunch Bar       174.384483
           Choco Coins Bag         197.140741
           Hazelnut Milk Bar        99.725240
           Milk Classic Bar         99.331996
           Mint Dark Bar            85.750413
           Mixed Assortment Box    228.297600
           Pralines Gift Box       118.735254
           Salted Caramel Bar      120.066265
           Truffle Gift Box        155.166667
           White Choco Bar         110.004464
Name: Boxes_Shipped, dtype: float64

In [99]:
##aggregate multiple functions 

grouped_agg = df.groupby('Country')['Price_per_Box'].agg(['mean','sum','count','sum'])
grouped_agg

               mean        sum  count        sum
Country
Australia  5.922007  547027.59  92372  547027.59
Brazil     5.890577  311317.01  52850  311317.01
Germany    5.933652  149533.97  25201  149533.97
India      5.908245  103293.85  17483  103293.85
Japan      5.880162   68427.44  11637   68427.44

In [100]:
grouped_agg = df.groupby('Country')['Price_per_Box'].agg(['sum','mean','count'])
grouped_agg

                 sum      mean  count
Country
Australia  547027.59  5.922007  92372
Brazil     311317.01  5.890577  52850
Germany    149533.97  5.933652  25201
India      103293.85  5.908245  17483
Japan       68427.44  5.880162  11637

In [106]:
### merging and joining Dataframes
## Create sample DataFrames

df1 = pd.DataFrame({'key' : ['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'key' : ['A','B','D'],'Value2':[4,5,6]})

In [102]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [107]:
df2

  key  Value2
0   A       4
1   B       5
2   D       6

In [ ]:
## Merge Dataframe on the 'key columns'

pd.merge(df1,df2,on="key",how='inner') ## inner will give only matching key value

  key  Value1  Value2
0   A       1       4
1   B       2       5

In [ ]:
pd.merge(df1,df2,on="key",how='outer') ## outer will give all key's value,if there have no value then give you 'NaN'

  key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [110]:
pd.merge(df1,df2,on="key",how='left')

  key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [112]:
pd.merge(df1,df2,on="key",how='right')

  key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6