### Read Data from Different Sources

In [28]:
import pandas as pd
from io import StringIO

Data = '{"Employee name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr.Developer"}]}'
df = pd.read_json(StringIO(Data))

In [29]:
df.to_json()

'{"Employee name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr.Developer"}}}'

In [30]:
df.to_json(orient='index')

'{"0":{"Employee name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr.Developer"}}}'

In [31]:
df.to_json(orient='records')

'[{"Employee name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr.Developer"}}]'

In [32]:
df_wine = pd.read_csv('WineQT.csv',header=None)

In [33]:
df_wine.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1,7.4,0.7,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
2,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.2,0.68,9.8,5,1
3,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.997,3.26,0.65,9.8,5,2
4,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.998,3.16,0.58,9.8,6,3

In [34]:
df_wine.to_csv("wine.csv")

In [38]:
url = 'https://www.fdic.gov/bank-failures/failed-bank-list'

df = pd.read_html(url)

In [ ]:
df[0]

In [52]:
url = 'https://en.wikipedia.org/wiki/Mobile_country_code'
headers = {'User-Agent': 'Mozilla/5.0'}

# Read directly using storage_options
tables = pd.read_html(url,match="Country",storage_options=headers)
tables[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A[edit] Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W[edit] Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y[edit] Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z[edit] Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [58]:
df_excel=pd.read_excel('sample_data.xlsx')
df_excel

     Name  Age
0  Vegeta   47
1    Goku   43
2   Gohan   24

In [60]:
df_excel.to_pickle('df_excel')

In [61]:
pd.read_pickle('df_excel')

     Name  Age
0  Vegeta   47
1    Goku   43
2   Gohan   24